Repository microsoft/TypeScript-Website-Localizations, pull requests merged in 2021-04, with the labels that each got.

#52 [PT-BR] Consumption.md
  docs/documentation/pt/declaration-files/Consumption.md
Labels: pt, translation

#67 [ko] Update ko/docs/handbook/utility-types.html
  docs/documentation/ko/reference/Utility Types.md
Labels: ko, translation

#68 Translate 1 file to ko - Generic Classes
  docs/playground/ko/JavaScript/Working With Classes/Generic Classes.ts
Labels: ko, translation

#69 Translate 1 file to ko - Mixins
  docs/playground/ko/JavaScript/Working With Classes/Mixins.ts
Labels: ko, translation

#70 Translate 1 file to zh - tsconfig.json
  docs/documentation/zh/project-config/tsconfig.json.md
Labels: translation, zh
