Repository microsoft/TypeScript-Website-Localizations, pull requests merged in 2021-03, with the labels that each got.

#56 Move pl/handbook-v1/The Handbook.md
  docs/documentation/pl/handbook-v2/The Handbook.md
Labels: pl, translation

#43 Translate 1 file to ko - Type Guards
  docs/playground/ko/TypeScript/Language/Type Guards.ts
Labels: ko, translation

#57 [PL] nightly builds translation
  docs/documentation/pl/Nightly Builds.md
Labels: pl, translation

#26 Update Japanese translation files
  docs/typescriptlang/ja/community.ts
  docs/typescriptlang/ja/handbook.ts
  docs/typescriptlang/ja/ja.ts
  docs/typescriptlang/ja/tsconfig.ts
Labels: jp, translation

#38 [ja] tsconfig/options, tsconfig/sections
  docs/tsconfig/ja/options/disableReferencedProjectLoad.md
  docs/tsconfig/ja/options/jsxFragmentFactory.md
  docs/tsconfig/ja/options/jsxImportSource.md
  docs/tsconfig/ja/options/noUncheckedIndexedAccess.md
  docs/tsconfig/ja/options/watchDirectory.md
  docs/tsconfig/ja/options/watchFile.md
  docs/tsconfig/ja/sections/compilerOptions.md
  docs/tsconfig/ja/sections/top_level.md
  docs/tsconfig/ja/sections/watchOptions.md
Labels: jp, translation

#47 Translate 1 file to ko - Union and Intersection Types
  docs/playground/ko/TypeScript/Primitives/Union and Intersection Types.ts
Labels: ko, translation

#53 Add files from old Korean repo to ko
  docs/documentation/ko/Nightly Builds.md
  docs/documentation/ko/declaration-files/By Example.md
  docs/documentation/ko/declaration-files/Consumption.md
  docs/documentation/ko/declaration-files/Deep Dive.md
  docs/documentation/ko/declaration-files/Do's and Don'ts.md
  docs/documentation/ko/declaration-files/Introduction.md
  docs/documentation/ko/declaration-files/Library Structures.md
  docs/documentation/ko/declaration-files/Publishing.md
  docs/documentation/ko/declaration-files/Templates.md
  docs/documentation/ko/get-started/TS for Functional Programmers.md
  docs/documentation/ko/get-started/TS for JS Programmers.md
  docs/documentation/ko/get-started/TS for OOPers.md
  docs/documentation/ko/get-started/TS for the New Programmer.md
  docs/documentation/ko/handbook-v2/The Handbook.md
  docs/documentation/ko/handbook-v2/Type Manipulation/Generics.md
  docs/documentation/ko/javascript/Creating DTS files From JS.md
  docs/documentation/ko/javascript/Intro to JS with TS.md
  docs/documentation/ko/javascript/JSDoc Reference.md
  docs/documentation/ko/javascript/Type Checking JavaScript Files.md
  docs/documentation/ko/project-config/Compiler Options in MSBuild.md
  docs/documentation/ko/project-config/Compiler Options.md
  docs/documentation/ko/project-config/Configuring Watch.md
  docs/documentation/ko/project-config/Integrating with Build Tools.md
  docs/documentation/ko/project-config/Project References.md
  docs/documentation/ko/project-config/tsconfig.json.md
  docs/documentation/ko/release-notes/TypeScript 3.8.md
  docs/documentation/ko/release-notes/TypeScript 3.9.md
  docs/documentation/ko/release-notes/TypeScript 4.0.md
Labels: ko, translation

#58 fix typo
  docs/documentation/pl/handbook-v2/The Handbook.md
Labels: pl, translation

#59 Add files from old Korean repo to ko
  docs/documentation/ko/declaration-files/templates/module-class.d.ts.md
  docs/documentation/ko/declaration-files/templates/module-function.d.ts.md
  docs/documentation/ko/reference/Decorators.md
  docs/documentation/ko/reference/Enums.md
  docs/documentation/ko/reference/Module Resolution.md
  docs/documentation/ko/reference/Modules.md
  docs/documentation/ko/reference/Namespaces and Modules.md
  docs/documentation/ko/reference/Namespaces.md
  docs/documentation/ko/reference/Type Compatibility.md
  docs/documentation/ko/reference/Variable Declarations.md
  docs/documentation/ko/tutorials/ASP.NET Core.md
  docs/documentation/ko/tutorials/DOM Manipulation.md
  docs/documentation/ko/tutorials/Gulp.md
  docs/documentation/ko/tutorials/Migrating from JavaScript.md
Labels: ko, translation

#48 Translate 1 file to ko - Assertion Functions
  docs/playground/ko/3-7/Types and Code Flow/Assertion Functions.ts
Labels: ko, translation

#49 Translate 1 file to ko - Tuples
  docs/playground/ko/TypeScript/Type Primitives/Tuples.ts
Labels: ko, translation
