Repository microsoft/TypeScript-Website-Localizations, pull requests merged in 2021-02, with the labels that each got.

#20 TSConfig Italian translation: added files
  docs/tsconfig/it/options/allowUnusedLabels.md
  docs/tsconfig/it/options/alwaysStrict.md
  docs/tsconfig/it/options/assumeChangesOnlyAffectDirectDependencies.md
  docs/tsconfig/it/options/baseUrl.md
  docs/tsconfig/it/options/charset.md
Labels: it, translation

#23 Translate 2 file to ko
  docs/playground/ko/Playground/Language/Fixits.ts
  docs/tsconfig/ko/options/plugins.md
Labels: ko, translation

#28 TSConfig Italian Translation: added some files
  docs/tsconfig/it/options/noEmit.md
  docs/tsconfig/it/options/outFile.md
  docs/tsconfig/it/options/plugins.md
Labels: it, translation

#29 TSConfig Italian Transaltion: Added few files
  docs/tsconfig/it/options/lib.md
  docs/tsconfig/it/options/outDir.md
  docs/tsconfig/it/options/removeComments.md
Labels: it, translation

#24 translation 2 files to Ko
  docs/tsconfig/ko/options/composite.md
  docs/tsconfig/ko/options/listFiles.md
Labels: ko, translation

#22 translation 4 files to Ko
  docs/playground/ko/3-7/Fixits/Infer From Usage Changes.ts
  docs/playground/ko/3-7/Syntax and Messaging/Flattened Error Reporting.ts
  docs/tsconfig/ko/options/jsxImportSource.md
  docs/tsconfig/ko/sections/top_level.md
Labels: ko, translation

#27 Translate 1 file to ko - Function Chaining
  docs/playground/ko/JavaScript/Functions with JavaScript/Function Chaining.ts
Labels: ko, translation

#33 TS Congfig Options Italian translation: Added some files.
  docs/tsconfig/it/options/target.md
  docs/tsconfig/it/options/tsBuildInfoFile.md
Labels: it, translation

#32 TSConfig Italian Translation: added some files
  docs/tsconfig/it/options/rootDir.md
  docs/tsconfig/it/options/sourceMap.md
Labels: it, translation

#35 TSConfig Italian Translation: Fixed oneline error
  docs/tsconfig/it/options/sourceMap.md
Labels: it, translation

#34 TSConfig Italian translation: added files
  docs/tsconfig/it/options/declarationDir.md
  docs/tsconfig/it/options/diagnostics.md
  docs/tsconfig/it/options/disableReferencedProjectLoad.md
  docs/tsconfig/it/options/disableSizeLimit.md
Labels: it, translation

#36 TSConfig Italian Transaltion: Few fixes
  docs/tsconfig/it/options/target.md
Labels: it, translation

#30 Translate 1 file to ko - Classes 101
  docs/playground/ko/JavaScript/Working With Classes/Classes 101.ts
Labels: ko, translation

#31 Translate 1 file to ko - Quick Fixes
  docs/playground/ko/JavaScript/Helping with JavaScript/Quick Fixes.ts
Labels: ko, translation

#39 Translate 1 file to ko - Code Flow
  docs/playground/ko/JavaScript/JavaScript Essentials/Code Flow.ts
Labels: ko, translation

#45 [PT-BR] explainFiles.md
  docs/tsconfig/pt/options/explainFiles.md
Labels: pt, translation

#44 [PT-BR] noPropertyAccessFromIndexSignature.md
  docs/tsconfig/pt/options/noPropertyAccessFromIndexSignature.md
Labels: pt, translation

#42 Translate 1 file to ko - Objects and Arrays
  docs/playground/ko/JavaScript/JavaScript Essentials/Objects and Arrays.ts
Labels: ko, translation

#40 Translate 1 file to ko - Errors
  docs/playground/ko/JavaScript/Helping with JavaScript/Errors.ts
Labels: ko, translation

#41 Translate 3 files to ko - out, outDir, outFile
  docs/tsconfig/ko/options/out.md
  docs/tsconfig/ko/options/outDir.md
  docs/tsconfig/ko/options/outFile.md
Labels: ko, translation
