Repository microsoft/TypeScript-Website-Localizations, pull requests merged in 2021-09, with the labels that each got.

#119 fix: correcting text in PT-br
  docs/playground/pt/TypeScript/Language Extensions/Types vs Interfaces.ts
Labels: pt, translation

#121 translated watchFile.md in Italian
  docs/tsconfig/it/options/watchFile.md
Labels: it, translation

#122 [ko] Handbook - Remove duplicate translations
  docs/documentation/ko/reference/Namespaces and Modules.md
Labels: ko, translation
