Repository microsoft/TypeScript-Website-Localizations, pull requests merged in 2021-08, with the labels that each got.

#111 fix(project-config): fix mistranslated sentence
  docs/documentation/ko/project-config/Project References.md
Labels: ko, translation

#72 [PT-BR] By Example.md and Do's and Dont's.md
  docs/documentation/pt/declaration-files/By Example.md
  docs/documentation/pt/declaration-files/Do's and Don'ts.md
Labels: pt, translation

#71 [PT-BR] Deep Dive
  docs/documentation/pt/declaration-files/Deep Dive.md
Labels: pt, translation

#80 Translate 1 file to ko. playground Indexed Types
  docs/playground/ko/TypeScript/Meta-Types/Indexed Types.ts
Labels: ko, translation

#91 Translate 1 file to ko - Mobile Support
  docs/playground/ko/Playground/Tooling/Mobile Support.ts
Labels: ko, translation

#81 Translate 1 file to ko. playground-Discriminate Types
  docs/playground/ko/TypeScript/Meta-Types/Discriminate Types.ts
Labels: ko, translation

#112 [PT-BR] Translate file Introduction
  docs/documentation/pt/declaration-files/Introduction.md
Labels: pt, translation

#113 Fix typo in JSX.md
  docs/documentation/id/reference/JSX.md
Labels: id, translation

#114 Translate FR: playground/fr/3-7/Syntax and messaging
  docs/playground/fr/3-7/Syntax and Messaging/Flattened Error Reporting.ts
  docs/playground/fr/3-7/Syntax and Messaging/Nullish Coalescing.ts
  docs/playground/fr/3-7/Syntax and Messaging/Optional Chaining.ts
Labels: translation, fr

#116 FR translation: fix typo
  docs/playground/fr/3-7/Syntax and Messaging/Optional Chaining.ts
Labels: translation, fr

#86 Translate 1 file to ko, playground - Nominal Typing
  docs/playground/ko/TypeScript/Language Extensions/Nominal Typing.ts
Labels: ko, translation

#82 Translate 1 file to ko playground - Conditional Types
  docs/playground/ko/TypeScript/Meta-Types/Conditional Types.ts
Labels: ko, translation
