Repository microsoft/TypeScript-Website-Localizations, pull requests merged in 2021-07, with the labels that each got.

#104 Translate fr playground sections.json
  docs/playground/fr/sections.json
Labels: fr, translation

#105 Translate 1 file to FR, typescriptlang - community
  docs/typescriptlang/fr/community.ts
Labels: fr, translation

#103 add french translated files
  docs/documentation/fr/Nightly Builds.md
  docs/tsconfig/fr/intro.md
Labels: fr, translation

#106 Translate to FR: playground/3-7/fixits
  docs/playground/fr/3-7/Fixits/Big number literals.ts
  docs/playground/fr/3-7/Fixits/Const to let.ts
  docs/playground/fr/3-7/Fixits/Infer From Usage Changes.ts
Labels: fr, translation

#109 translate Angular.md file
  docs/documentation/fr/tutorials/Angular.md
  docs/documentation/fr/tutorials/React.md
Labels: fr, translation

#110 Translate to FR: typescriptlang directory
  docs/typescriptlang/fr/dt.ts
  docs/typescriptlang/fr/fr.ts
  docs/typescriptlang/fr/handbook.ts
  docs/typescriptlang/fr/head-seo.ts
  docs/typescriptlang/fr/nav.ts
  docs/typescriptlang/fr/tsconfig.ts
Labels: fr, translation

#89 Translate 1 file to ko - Typescript Version
  docs/playground/ko/Playground/Tooling/TypeScript Versions.ts
Labels: ko, translation

#97 Translate 1 file to ko, TSConfig - noResolve
  docs/tsconfig/ko/options/noResolve.md
Labels: ko, translation

#96 Translate 1 file to ko, TSConfig - moduleResolution
  docs/tsconfig/ko/options/moduleResolution.md
Labels: ko, translation

#37 zh: improve translations
  docs/playground/zh/JavaScript/External APIs/TypeScript with React.tsx
  docs/playground/zh/JavaScript/JavaScript Essentials/Hello World.ts
  docs/playground/zh/JavaScript/JavaScript Essentials/Objects and Arrays.ts
  docs/playground/zh/JavaScript/Working With Classes/Generic Classes.ts
  docs/playground/zh/Playground/Config/JavaScript Playgrounds.js
  docs/playground/zh/Playground/Config/New Compiler Defaults.ts
  docs/playground/zh/Playground/Language/Automatic Type Acquisition.ts
  docs/playground/zh/Playground/Language/Fixits.ts
  docs/playground/zh/Playground/Tooling/Mobile Support.ts
  docs/playground/zh/Playground/Tooling/Sharable URLs.ts
  docs/playground/zh/Playground/Tooling/TypeScript Versions.ts
  docs/playground/zh/sections.json
  docs/typescriptlang/zh/documentation.ts
  docs/typescriptlang/zh/head-seo.ts
  docs/typescriptlang/zh/index.ts
  docs/typescriptlang/zh/nav.ts
  docs/typescriptlang/zh/playground.ts
Labels: translation, zh
