Repository microsoft/TypeScript-Website-Localizations, pull requests merged in 2022-02, with the labels that each got.

#135 Apply 7313a8e202ddddbea4572d105dc628ce81cc9982 -> #125
  docs/playground/ko/3-7/Types and Code Flow/Uncalled Function Checks.ts
Labels: ko, translation

#134 [PT-BR] global-modifying-modules.d.ts
  docs/documentation/pt/declaration-files/templates/global-modifying-module.d.ts.md
Labels: pt, translation

#117 Add translation file to ko - Structural Typing
  docs/playground/ko/TypeScript/Language/Structural Typing.ts
Labels: ko, translation

#137 French Translation: "TS for OOP programmers" page
  docs/documentation/fr/get-started/TS for OOPers.md
Labels: translation, fr
