Repository microsoft/TypeScript-Website-Localizations, pull requests merged in 2022-09, with the labels that each got.

#141 Translate 1 file to ko - Keyof Type Operator.md
  docs/documentation/ko/handbook-v2/Type Manipulation/Keyof Type Operator.md
Labels: ko, translation

#164 Remove span tag in title and unnecessary TOC in Ko
  docs/documentation/ko/release-notes/TypeScript 3.8.md
  docs/documentation/ko/release-notes/TypeScript 3.9.md
Labels: ko, translation

#159 translate TS for JS Programmers.md in zh-CN
  docs/documentation/zh/get-started/TS for JS Programmers.md
Labels: zh, translation

#168 Fix typo in Everyday Types in Korean
  docs/documentation/ko/handbook-v2/Everyday Types.md
Labels: ko, translation

#170 fix: fixes the word 'Programados' to 'Programador'
  docs/documentation/pt/get-started/TS for the New Programmer.md
Labels: pt, translation

#151 Fix mistranslated sentence
  docs/documentation/ko/tutorials/Babel with TypeScript.md
Labels: ko, translation
